---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pipenv sync --dev
      - run: pipenv run migrate
      - run: pipenv run python manage.py test


workflows:
  version: 2
  commit:
    jobs:
      - build
