# Generated by Django 2.2.7 on 2020-01-15 07:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or short description of the event', max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Full description of the event', verbose_name='Description')),
                ('recurrences', recurrence.fields.RecurrenceField(blank=True, default=None, help_text='This event occurs more than once.', verbose_name='Event Recurrence')),
                ('start_datetime', models.DateTimeField(help_text='When does the event start?', verbose_name='Event Start Time')),
                ('end_datetime', models.DateTimeField(help_text='When does the event end?', verbose_name='Event End Time')),
                ('organization_name', models.CharField(help_text='Name of the hosting organization', max_length=100, verbose_name='Organization Name')),
                ('event_type', models.CharField(choices=[('Workshop', 'Workshop'), ('Tabling', 'Tabling'), ('Celebration', 'Celebration'), ('Drop-in center', 'Drop-in center'), ('Other', 'Other')], max_length=20)),
                ('site_name', models.CharField(blank=True, default=None, help_text='Name of the location where the event will take place', max_length=100, null=True, verbose_name='Location Name')),
                ('location', models.CharField(help_text='Postal address where the event will take place', max_length=100, verbose_name='Location Address')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Latitude')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_census_equipped', models.BooleanField(default=False, help_text='Is this event technologically equipped to allow people to take the census?', verbose_name='Census Equipment')),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Vietnamese', 'Vietnamese'), ('Chinese', 'Chinese'), ('Tagalog', 'Tagalog')], help_text='Add languages supported at the event', max_length=42)),
                ('contact_name', models.CharField(help_text='Name of contact for event', max_length=100, null=True, verbose_name='Contact Name')),
                ('contact_email', models.EmailField(help_text='Email for contact', max_length=60, null=True, verbose_name='Contact Email')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for contact', max_length=128, null=True, region=None, verbose_name='Contact Phone Number')),
                ('is_private_event', models.BooleanField(default=False, help_text='Would you like to hide this event from the public?', verbose_name='Private Event')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(max_length=100)),
                ('published', models.DateTimeField(help_text='Time when the Event was published')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_event', to='census.Event')),
            ],
        ),
    ]
