# Generated by Django 2.2.1 on 2019-05-11 20:57

import census.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[(census.constants.EventApprovalStatus('Pending'), 'Pending'), (census.constants.EventApprovalStatus('Approved'), 'Approved')], default=census.constants.EventApprovalStatus('Pending'), max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_census_equipped',
            field=models.BooleanField(default=False, help_text='Is this event technologically equipped to allow people to take the census?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
