# Generated by Django 2.2.7 on 2020-01-16 03:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='', help_text='City where the event will take place', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_ada_compliant',
            field=models.BooleanField(default=False, help_text='Is the event compliant with the Americans with Disabilities Act?'),
        ),
        migrations.AddField(
            model_name='event',
            name='zip_code',
            field=models.CharField(default='', help_text='Zip code of where the event will take place', max_length=20, verbose_name='Zip Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email for contact', max_length=60, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Name of contact for event', max_length=100, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number for contact', max_length=128, null=True, region=None, verbose_name='Contact Phone Number'),
        ),
    ]
