# Generated by Django 2.2.7 on 2020-01-18 20:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20200115_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Questionnaire Assistance Center', 'Questionnaire Assistance Center'), ('Information Booth', 'Information Booth'), ('Informational Meeting', 'Informational Meeting'), ('Census Completion Workshop', 'Census Completion Workshop'), ('Town Hall', 'Town Hall'), ('Block Party', 'Block Party'), ('Webinar', 'Webinar'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Mandarin', 'Mandarin'), ('Cantonese', 'Cantonese'), ('Tagalog', 'Tagalog'), ('Hindi', 'Hindi'), ('Vietnamese', 'Vietnamese'), ('Punjabi', 'Punjabi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Korean', 'Korean'), ('Arabic', 'Arabic'), ('Farsi', 'Farsi'), ('Dari', 'Dari')], help_text='Add languages supported at the event', max_length=105),
        ),
    ]
