# Generated by Django 2.2.1 on 2019-05-11 20:59

import census.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20190511_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default=census.constants.EventApprovalStatus('Pending'), max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('TABLING', 'Tabling'), ('CELEBRATION', 'Celebration'), ('DROPIN', 'Drop-in center'), ('OTHER', 'Other')], max_length=2),
        ),
    ]
