# Generated by Django 2.2.1 on 2019-05-11 22:16

import census.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20190511_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[(census.constants.EventApprovalStatus('Pending'), 'Pending'), (census.constants.EventApprovalStatus('Approved'), 'Approved')], max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[(census.constants.EventType('Workshop'), 'Workshop'), (census.constants.EventType('Tabling'), 'Tabling'), (census.constants.EventType('Celebration'), 'Celebration'), (census.constants.EventType('Drop-in center'), 'Drop-in center'), (census.constants.EventType('Other'), 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_census_equipped',
            field=models.BooleanField(help_text='Is this event technologically equipped to allow people to take the census?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Location where the event will take place', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_name',
            field=models.CharField(help_text='Name of the hosting organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(help_text='When does this event start?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Title or short description of the event', max_length=100),
        ),
    ]
