# Generated by Django 2.2.1 on 2019-06-10 16:30

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_auto_20190511_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, default=''),
        ),
    ]
