# Generated by Django 2.2.1 on 2019-05-11 22:36

import census.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_auto_20190511_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[(census.constants.EventApprovalStatus('Pending'), 'Pending'), (census.constants.EventApprovalStatus('Approved'), 'Approved')], max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('TABLING', 'Tabling'), ('CELEBRATION', 'Celebration'), ('DROPIN', 'Drop-in center'), ('OTHER', 'Other')], default='OTHER', max_length=2),
        ),
    ]
