# Generated by Django 2.2.3 on 2019-07-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_googleevent'),
        ('census', '0005_event_recurrences'),
    ]

    operations = [
    ]
