# Generated by Django 2.2.1 on 2019-05-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_auto_20190511_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('TABLING', 'Tabling'), ('CELEBRATION', 'Celebration'), ('DROPIN', 'Drop-in center'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
