# Generated by Django 2.2.3 on 2019-08-31 22:21

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_merge_20190710_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='00:00', help_text='What time does the event end? HH:MM:AM/PM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='00:00', help_text='What time does this event start? HH:MM:AM/PM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, help_text='Enter date of the event or information on a recurring event'),
        ),
        migrations.AlterField(
            model_name='googleevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_event', to='census.Event'),
        ),
    ]
