# Generated by Django 2.2.1 on 2019-05-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20190511_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='When does the event end?', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
