# Generated by Django 2.2.7 on 2019-11-10 20:07

from django.db import migrations
import multiselectfield.db.fields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20190831_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish'), ('VIETNAMESE', 'Vietnamese'), ('CHINESE', 'Chinese'), ('TAGALOG', 'Tagalog')], default='Languages.ENGLISH', max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, help_text='Add date of the event or rules for a recurring event', verbose_name='Date Information'),
        ),
    ]
