# Generated by Django 2.2.4 on 2019-11-03 21:58

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20190831_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, help_text='Add date of the event or rules for a recurring event', verbose_name='Date Information'),
        ),
    ]
