# Generated by Django 2.2.3 on 2019-10-06 23:45

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20190831_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrences',
        ),
        migrations.AddField(
            model_name='event',
            name='date_information',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, help_text='Add date of the event or rules for a recurring event'),
        ),
    ]
