# Generated by Django 2.2.7 on 2019-11-10 23:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_auto_20191110_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(help_text='Email for contact', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_name',
            field=models.CharField(help_text='Name of contact for event', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
