# Generated by Django 2.2.7 on 2019-11-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0009_auto_20191110_1251'),
        ('census', '0009_auto_20191110_1504'),
    ]

    operations = [
    ]
