# Generated by Django 2.2.7 on 2019-11-12 22:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_merge_20191111_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(help_text='Email for contact', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for contact', max_length=128, null=True, region=None),
        ),
    ]
