# Generated by Django 2.2.7 on 2019-11-16 22:57

import datetime
from django.db import migrations, models
import recurrence.fields
import pytz



class Migration(migrations.Migration):

    dependencies = [
        ('census', '0012_auto_20191113_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 17, 30, tzinfo=pytz.timezone('America/Los_Angeles')), help_text='When does the event end?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 16, 0, tzinfo=pytz.timezone('America/Los_Angeles')), help_text='When does the event start?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, help_text='This event occurs more than once.'),
        ),
    ]
