# Generated by Django 2.2.7 on 2019-11-21 06:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_auto_20191116_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('es', 'Spanish'), ('vi', 'Vietnamese'), ('zh-cn', 'Chinese'), ('tl', 'Tagalog')], help_text='Add languages supported at the event', max_length=17),
        ),
    ]
