# Generated by Django 2.2.7 on 2019-12-04 22:43

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_auto_20191116_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private_event',
            field=models.BooleanField(default=False, help_text='Would you like to hide this event from the public?', verbose_name='Private Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(help_text='Email for contact', max_length=60, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_name',
            field=models.CharField(help_text='Name of contact for event', max_length=100, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for contact', max_length=128, null=True, region=None, verbose_name='Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Full description of the event', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(help_text='When does the event end?', verbose_name='Event End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('TABLING', 'Tabling'), ('CELEBRATION', 'Celebration'), ('DROPIN', 'Drop-in center'), ('OTHER', 'Other')], max_length=20, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_census_equipped',
            field=models.BooleanField(default=False, help_text='Is this event technologically equipped to allow people to take the census?', verbose_name='Census Equipment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish'), ('VIETNAMESE', 'Vietnamese'), ('CHINESE', 'Chinese'), ('TAGALOG', 'Tagalog')], help_text='Add languages supported at the event', max_length=42, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Location where the event will take place', max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_name',
            field=models.CharField(help_text='Name of the hosting organization', max_length=100, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, help_text='This event occurs more than once.', verbose_name='Event Recurrence'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(help_text='When does the event start?', verbose_name='Event Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Title or short description of the event', max_length=100, verbose_name='Title'),
        ),
    ]
