# Generated by Django 2.2.8 on 2019-12-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0015_event_is_private_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='site_name',
            field=models.CharField(blank=True, default=None, help_text='Name of the location where the event will take place', max_length=100, null=True, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Postal address where the event will take place', max_length=100, verbose_name='Location Address'),
        ),
    ]
